name: dev merge
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    branches:
      - 'dev'
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    env:
      apps: {'app1': {'key1': 'value1'}, 'app2': {'key1': 'value1'}}
    strategy:
      matrix:
        app: ['app1', 'app2', 'app3']
    steps:
      - uses: actions/checkout@v3
      - run: echo $app
        env:
          app: ${{ matrix.app }}
      - run: echo $app
        env:
          key: env.apps.${{ matrix.app }}
# jobs: 
#   if_pushed: 
#     runs-on: ubuntu-latest 
#     steps: 
#       - uses: actions/checkout@v3
#       - run: | 
#            echo The PR was pushed
#       - run: | 
#            ls -l
#       - name: Dump GitHub context
#         id: github_context_step
#         run: echo '${{ github['event']['commits'][0]['message'] }}'
      # - name: Dump job context
      #   run: echo '${{ toJSON(job) }}'
      # - name: Dump steps context
      #   run: echo '${{ toJSON(steps) }}'
      # - name: Dump runner context
      #   run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'
