name: dev merge
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  pull_request: 
    types: 
      - closed
    branches:
      - 'dev'
jobs: 
  if_merged: 
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest 
    steps: 
      - run: | 
           echo The PR was merged
