name: dev merge
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  pull_request: 
    types: 
      - closed
    branches:
      - 'dev'
jobs: 
  if_merged: 
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3
      - run: | 
           echo The PR was merged
      - run: | 
           ls -l
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'